[package]
name = "riot-sys"
version = "0.1.0"
authors = ["Ben Stuart <mail@bstuart.de>"]
build = "build.rs"

[build-dependencies]
bindgen = "0.36.0"
git2 = "0.7.1"

[features]
default = []
sam_common = []

[dependencies]
cty = "0.1.5"

