[all]
common = [
	"-DDONT_USE_CMSIS_INIT",
	"-IRIOT/core/include",
	"-IRIOT/sys/include",
	"-IRIOT/drivers/include",
]

[board.samr21-xpro]
model = "-DCPU_MODEL_SAMR21G18A"
defines = []
includes = [
	"-IRIOT/cpu/cortexm_common/include",
	"-IRIOT/cpu/cortexm_common/include/vendor",
	"-IRIOT/cpu/sam0_common/include/",
	"-IRIOT/cpu/samd21/include",
	"-IRIOT/cpu/sam0_common/include/vendor/samr21/include",
	"-IRIOT/cpu/sam0_common/include/vendor/samr21/include/component",
	"-IRIOT/boards/samr21-xpro/include",
	"-IRIOT/cpu/samr21-xpro/include",
]
